name: Valist Publish
on:
  push:
    branches:
      - main
jobs:
  valist-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1'

      - name: Build multi-platform Go binary
        run: |
          cd multi-platform-project
          make

      - run: echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Valist Publish
        uses: valist-io/valist-github-action@dev
        with:
          private-key: ${{ secrets.VALIST_SIGNER }}
          rpc-url: "https://rpc.valist.io/mumbai"

          account: acme-co
          project: multi-platform
          release: gha-${{ env.TIMESTAMP }}

          # configures platform support for web, mac, linux, and windows
          platform-web: multi-platform-project/dist/web
          platform-darwin-amd64: multi-platform-project/dist/darwin/amd64/hello-go
          platform-darwin-arm64: multi-platform-project/dist/darwin/arm64/hello-go
          platform-linux-amd64: multi-platform-project/dist/linux/amd64/hello-go
          platform-windows-amd64: multi-platform-project/dist/windows/amd64/hello-go
